
spring:
  #redis连接配置
  redis:
    host: 182.92.160.192
    port: 6379
    password: xi789156/
  servlet:
    multipart:
      max-file-size: 20MB
  main:
    allow-circular-references: true

  #配置数据库
  datasource:
    url: jdbc:mysql://localhost:3306/typhoon?uesSSL=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      connection-init-sqls: SET NAMES utf8mb4
#    type: org.apache.commons.dbcp2.BasicDataSource


#MP配置：逻辑删除，日志等
mybatis-plus:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/com/xxx/typhoon/app/mapper/xml/*.xml
  type-aliases-package: com.xxx.app.entity
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8081
  max-http-header-size: 1024000
